<a href="https://colab.research.google.com/github/pabloochocobar/CE888/blob/main/Labs/Lab5/Recommender_Systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv",header=None)
print(df)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


In [ ]:
#df.drop(df.columns[0], inplace=True, axis=1)
df=df.drop(df.columns[0],1)
print(df)

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


In [ ]:
arr = df.values
print(arr.shape)

(24983, 100)


In [ ]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [ ]:
def replace(orig, percentage=0.1):
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [ ]:
new_arr, idx = replace(arr, 0.1)

In [ ]:
arr[idx[0][0], idx[1][0]]

-0.24

In [ ]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [ ]:
n_latent_factors = 5

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [ ]:
latent_item_features

array([[8.58671450e-02, 7.78818110e-01, 1.07567381e-02, 6.99353881e-01,
        9.17866797e-01],
       [1.72865150e-01, 7.63915384e-01, 9.53126605e-01, 4.92825564e-01,
        5.89360902e-01],
       [6.91543231e-01, 1.01462488e-01, 1.80988572e-01, 3.76411381e-01,
        9.94321391e-02],
       [3.75293087e-01, 6.33157410e-01, 5.49927783e-01, 8.49007775e-01,
        6.10502691e-01],
       [6.54057245e-01, 4.09231661e-01, 8.12368245e-01, 6.11579886e-01,
        8.61862969e-01],
       [2.61862384e-01, 3.84874127e-01, 7.69791289e-02, 3.34952899e-02,
        9.48363242e-02],
       [1.29336936e-01, 5.04180739e-01, 5.75305322e-01, 2.93923850e-01,
        2.51176127e-01],
       [8.81081720e-01, 6.50581962e-01, 1.94067812e-01, 8.28662697e-01,
        9.65026290e-01],
       [4.12757651e-01, 3.70524303e-01, 5.77596331e-01, 4.27572369e-01,
        1.76571064e-01],
       [8.48165783e-01, 7.45579674e-01, 6.10955755e-01, 5.96274042e-01,
        6.89059707e-01],
       [7.70482669e-01, 8.8982

In [ ]:
latent_user_preferences

array([[0.31593099, 0.14705325, 0.2731024 , 0.84499645, 0.2704683 ],
       [0.50008583, 0.93179842, 0.00464416, 0.3031402 , 0.70792341],
       [0.04039463, 0.42350754, 0.99113636, 0.14892749, 0.94791984],
       ...,
       [0.58492756, 0.15830043, 0.11007567, 0.17503485, 0.90302801],
       [0.52941921, 0.4552806 , 0.64827661, 0.98442078, 0.80328031],
       [0.47694215, 0.70000589, 0.45036067, 0.93077315, 0.10421058]])

In [ ]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=50):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = new_arr[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        #if (iteration % 10000) == 0:
        print(mse)

In [ ]:
sgd()

25.580586745520264
24.978894296597517
24.879884301294375
24.788219276594134
24.69618146000717
24.603066139229686
24.5084721531009
24.411954856668252
24.31292473015803
24.210542858372165
24.103584248332105
23.990254261232007
23.867945217919747
23.732926350497106
23.579979087329676
23.40203400277299
23.189953800764545
22.932753086828956
22.61872898134562
22.238067828486102
21.78717785652396
21.27387722498531
20.72076146562681
20.16311684272698
19.640011614405253
19.182420153518084
18.805388238980274
18.508117750782016
18.279738399482255
18.105879826623493
17.972987587047506
17.870082361460714
17.788937116587018
17.72361651840567
17.669902114874553
17.624801456986606
17.58618047654928
17.552502906197283
17.522649607926272
17.49579412773799
17.471316909008607
17.448745893142814
17.427715126977258
17.407935693769296
17.38917511609974
17.371242615114323
17.353978444521086
17.33724608143489
17.320926438085806
17.304913517972334


In [ ]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-3.58673617, -4.95520958, -5.191049  , ..., -3.7663032 ,
        -5.37594025, -3.17382937],
       [ 2.89438651,  3.3832804 ,  3.42398053, ...,  3.55589826,
         3.52189866,  3.43735093],
       [ 6.16271039,  6.55908741,  6.28293728, ...,  6.37696686,
         5.17645576,  7.18591893],
       ...,
       [-1.16896713, -1.87405548, -2.04625384, ..., -0.66066784,
        -1.93783465, -0.54499132],
       [-0.90837806, -1.86124491, -1.99157693, ..., -1.06203334,
        -2.35181725, -0.31170108],
       [ 3.1277973 ,  2.96404804,  2.90429579, ...,  3.36381412,
         2.43335754,  4.01060659]])

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [ ]:
comparison_data

1    ...                           100
0      (-7.82, -3.586736174065686)  ...    (99.0, -3.173829374597084)
1       (4.08, 2.8943865109181797)  ...     (1.07, 3.437350934549974)
2        (99.0, 6.162710385924822)  ...     (99.0, 7.185918932107753)
3       (99.0, 1.8697815524318029)  ...    (99.0, 2.5139791671401586)
4        (8.5, 2.9339684940362614)  ...      (1.6, 4.190949819142647)
...                            ...  ...                           ...
24978    (0.44, 2.490204607955913)  ...    (7.43, 3.7143895933274096)
24979     (9.13, 2.09916722805852)  ...    (8.45, 2.2130802593253716)
24980  (99.0, -1.1689671273507027)  ...    (99.0, -0.544991317307788)
24981  (99.0, -0.9083780615524011)  ...  (99.0, -0.31170108075315867)
24982    (2.43, 3.127797299374814)  ...     (99.0, 4.010606594558495)

[24983 rows x 100 columns]